### PR TITLE
Migration to .net 6

### PR DESCRIPTION
**Pull request by tecnocrata**
Hey dudes,
Here my contribution to your repo, I have migrated the references and packages to .net 6.0

### CODE REVIEW

**Comment by JavierCane** [comment]
Hi!

Thanks a lot for the contribution!

Would it be possible to also update [the GitHub Actions Workflow](https://github.com/CodelyTV/csharp-ddd-skeleton/blob/master/.github/workflows/workflow.yml)?

Thx!!

**Comment by tecnocrata** [comment]
Sure, I will try

**Comment by tecnocrata** [comment]
Everything is working now @JavierCane

**Comment by JavierCane** [comment]
🎉

merging!

**Pull request merged**
